[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.12.1"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[build.processing]
  skip_processing = true

[dev]
  framework = "vite"
  target = "static"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev.environment]
  # Variables de entorno de desarrollo
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
